let rootHandle=null,pdfs=[];
const $=id=>document.getElementById(id),status=$('status'),body=$('pdfBody'),count=$('countText');
$('versionBadge').textContent=`v${APP_VERSION}`;document.title=`논문 PDF 관리 · v${APP_VERSION}`;
const fmt=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
async function walk(dir,prefix=''){const out=[];for await(const [name,h] of dir.entries()){const path=prefix?`${prefix}/${name}`:name;if(h.kind==='directory')out.push(...await walk(h,path));else if(h.kind==='file'&&name.toLowerCase().endsWith('.pdf')){const f=await h.getFile();out.push({name,path,size:f.size})}}return out}
async function scan(prompt=true){if(!rootHandle)return;if(!await ensurePermission(rootHandle,'readwrite',prompt)){status.textContent='폴더 읽기/쓰기 권한이 필요합니다.';return}status.textContent=`"${rootHandle.name}" 검색 중...`;pdfs=await walk(rootHandle);pdfs.sort((a,b)=>a.path.localeCompare(b.path,'ko'));$('scanBtn').disabled=false;render();status.textContent=`PDF ${pdfs.length}개를 찾았습니다.`}
function render(){const q=$('searchBox').value.trim().toLowerCase(),arr=pdfs.filter(x=>x.name.toLowerCase().includes(q)||x.path.toLowerCase().includes(q));count.textContent=`PDF ${arr.length}개`;body.replaceChildren();if(!arr.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.className='empty';td.textContent='PDF가 없습니다.';tr.append(td);body.append(tr);return}for(const x of arr){const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td'),c=document.createElement('td'),d=document.createElement('td'),btn=document.createElement('button');a.textContent=x.name;b.textContent=x.path;b.className='path';c.textContent=fmt(x.size);btn.className='open-btn';btn.textContent='PDF 열기';btn.onclick=()=>{const u=new URL('./pdf-editor/index.html',location.href);u.searchParams.set('file',x.path);window.open(u.toString(),'_blank')};d.append(btn);tr.append(a,b,c,d);body.append(tr)}}
$('searchBox').oninput=render;
$('chooseBtn').onclick=async()=>{try{rootHandle=await showDirectoryPicker({id:'paper-library-root',mode:'readwrite'});await saveRootHandle(rootHandle);await scan(true)}catch(e){if(e.name!=='AbortError')alert(e.message)}};
$('reopenBtn').onclick=async()=>{rootHandle=await loadRootHandle();if(!rootHandle)return alert('저장된 폴더가 없습니다.');await scan(true)};
$('scanBtn').onclick=()=>scan(true);
(async()=>{const saved=await loadRootHandle();if(saved){rootHandle=saved;if(await ensurePermission(saved,'readwrite',false))await scan(false);else status.textContent=`이전에 선택한 폴더 "${saved.name}"가 저장되어 있습니다.`}})().catch(e=>{console.error(e);alert(e.message)});
